services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - bank_network
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - bank_network
  
  bank-db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_USER: bank_man
      POSTGRES_DB: bank_db
      POSTGRES_PASSWORD: bank_password
    ports:
      - '5432:5432'
    volumes:
      - bank_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - bank_network
  bank-producer:
    build: .
    command: python producer.py
    depends_on:
      - kafka
      - bank-db
    networks:
      - bank_network
  bank-consumer:
    build: .
    command: python consumer.py
    depends_on:
    - kafka
    - bank-db
    networks:
      - bank_network
  airflow-init:
    image: apache/airflow:2.9.0
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /opt/airflow/dags
        airflow db init
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bank_man:bank_password@bank-db:5432/airflow_db
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - bank_network

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - airflow-init
      - bank-db
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bank_man:bank_password@bank-db:5432/airflow_db
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - bank_network
      
  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow-webserver
    restart: always
    depends_on:
      - airflow-scheduler
      - bank-db
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=your_fernet_key_here
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://bank_man:bank_password@bank-db:5432/airflow_db
    command: webserver
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - bank_network

volumes:
  bank_data:
networks:
  bank_network:
    driver: bridge